
services:
  backend:
    image: laravelsail/php84-composer
    container_name: laravel-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    # command: bash -c "composer install && php artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    image: node:18
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
